{{ $namespace := env "NAMESPACE" | default "default"}}
{{ $release_name := env "RELEASE_NAME" | default "golang-app"}}
{{- $env_name := env "ENV_NAME" | default "dev" }}

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: {{ $release_name }}-mysql-db
  namespace: {{ $namespace }}
  chart: bitnami/mysql
  version: "10.2.2"
  values:
  - ./values/mysql/{{ $env_name }}/values.yaml
