{{ $namespace := env "NAMESPACE" | default "default"}}
{{ $release_name := env "RELEASE_NAME" | default "golang-app"}}
{{- $env_name := env "ENV_NAME" | default "dev" }}

releases:
- name: {{ $release_name }}-deployment
  namespace: {{ $namespace }}
  chart: ./chart
  version: "0.1.0"
  values:
  - ./values/app/{{ $env_name }}/values.yml
  - ./values/app/{{ $env_name }}/secrets/secrets.yml
  - ./values/app/{{ $env_name }}/val1/val1.yml
  - ./values/app/{{ $env_name }}/val2/val2.yml
  set:
  - name: "image.backendRepository"
    value: {{ requiredEnv "repository" }}
  - name: "image.tag"
    value: {{ requiredEnv "tag" }}
