name: Docker Image Build and Push Workflow

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Enter Image tag"
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name:
          - ${{ vars.DOCKER_DEV_IMAGE_NAME }}
          - ${{ vars.DOCKER_PROD_IMAGE_NAME }}
    steps:
    - name: Checkout to Code
      uses: actions/checkout@v4

    - name: Call Composite Action
      id: build-and-push-id
      uses: mokhlesurr031/gh-tutorial-docker-build-and-push@v1
      with:
        dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
        dockerhub-token: ${{ secrets.DOCKERHUB_SECRETS }}
        image-name: ${{ matrix.image-name }}
        image-tag: ${{ github.event.inputs.image_tag }}
        dockerfile-path: "Dockerfile"

    - name: Print Result
      run: |
        echo "Build and Push Result is: ${{ steps.build-and-push-id.outputs.result }}"