name: Pluto
on:
  push:

jobs:
  pluto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@master
      
      - name: Use pluto
        run: |
          ls -lha
          pluto detect-files -d deployment
        