name: Test Helmfile Deploy

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: "Deployment Environment Name:"
        required: true
        type: choice
        options:
          - dev
          - prod
        default: dev

      image_tag:
        description: "Enter Image tag"
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Code
        uses: actions/checkout@v4

      - name: Install Helm, Helmfile and Helm Diff Plugin
        run: |
          # Install Helm
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm

          # Install Helm Diff Plugin
          helm plugin add https://github.com/databus23/helm-diff

          # Install Helmfile
          HELMFILE_VERSION="0.159.0"  # Update to the latest version
          HELMFILE_URL="https://github.com/helmfile/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_${HELMFILE_VERSION}_linux_amd64.tar.gz"
          curl -Lo helmfile.tar.gz $HELMFILE_URL
          tar xzf helmfile.tar.gz -C /tmp
          sudo mv /tmp/helmfile /usr/local/bin/
          chmod +x /usr/local/bin/helmfile
          rm helmfile.tar.gz

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup Local Test Cluster using Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind create cluster --name test-cluster
          kubectl cluster-info --context kind-test-cluster

      - name: Test Deploy in "${{ inputs.env_name }}" Environment (Diff)
        run: |
          if [ "${{ inputs.env_name }}" = "dev" ]; then
            image_name="docker.io/fnmahin/helmfile-dev-repo"
          elif [ "${{ inputs.env_name }}" = "prod" ]; then
            image_name="docker.io/fnmahin/helmfile-prod-repo"
          else
            echo "Invalid env_name. Must be 'dev' or 'prod'."
            exit 1
          fi

          export ENV_NAME="${{ inputs.env_name }}"
          export tag="${{ inputs.image_tag }}"
          export repository="$image_name"

          cd deployment
          # Check Chart Template
          helmfile --kube-context kind-test-cluster template
          # Check Diff from the currently running release
          helmfile --kube-context kind-test-cluster diff
          # Deploy
          # helmfile --kube-context kind-test-cluster sync
