name: Test Helmfile Deploy

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: "Deployment Environment Name:"
        required: true
        type: choice
        options:
          - dev
          - prod
        default: dev

      image_tag:
        description: "Enter Image tag"
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Code
        uses: actions/checkout@v4

      - name: Install Helm, Helmfile and Helm Diff Plugin
        run: |
          # Install Helm
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm

          # Install helm-fill plugin
          helm plugin add https://github.com/databus23/helm-diff

          # Install helmfile
          curl -L https://github.com/helmfile/helmfile/releases/download/v0.15.0/helmfile_0.15.0_linux_amd64.tar.gz | tar xz -C /usr/local/bin
          chmod +x /usr/local/bin/helmfile


      - name: Test Deploy (Diff)
        run: |
          if [ "${{ inputs.env_name }}" = "dev" ]; then
            image_name="docker.io/fnmahin/helmfile-dev-repo"
          elif [ "${{ inputs.env_name }}" = "prod" ]; then
            image_name="docker.io/fnmahin/helmfile-prod-repo"
          else
            echo "Invalid env_name. Must be 'dev' or 'prod'."
            exit 1
          fi

          export env_name="${{ inputs.env_name }}"
          export tag="${{ inputs.image_tag }}"
          export repository="$image_name"

          cd deployment
          helmfile diff
